[versions]
agp = "8.3.0-rc01"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.1.4"

[libraries]
appcompat = "androidx.appcompat:appcompat:1.7.0"
activity = "androidx.activity:activity:1.9.2"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
junit = "junit:junit:4.13.2"
ext-junit = "androidx.test.ext:junit:1.2.1"
espresso-core = "androidx.test.espresso:espresso-core:3.6.1"
# material-button = "com.google.android.material:material-button:1.12.0" # Add if needed

[plugins]
androidApplication = { id = "com.android.application", version = "8.5.0" }